```
name: CiCdDemo

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install fastlane

      - name: Build and test
        run: |
          fastlane test

      - name: Deploy to TestFlight
        run: |
          fastlane deploy
```
